apiVersion: v1
kind: Service
metadata:
  name: booklore-app-service
  namespace: booklore
  labels:
    app: booklore-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: booklore-app

---
apiVersion: v1
kind: Service
metadata:
  name: booklore-redis
  namespace: booklore
  labels:
    app: booklore-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: booklore-redis